// NPCVariance.cs
// A mutagen synthesis patcher that randomizes the height of all human NPCs in a deterministic manner
// The patcher can be configured with a minimum and maximum value for each race and gender of that race

using Mutagen.Bethesda;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace NPCVariance
{
    public class Program
    {
        static Lazy<Settings> _settings = null!;
        static public Settings settings => _settings.Value;
        public static async Task<int> Main(string[] args)
        {

            // Run the patcher
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "NPCVariance.esp")
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .Run(args);
        }

        // A method to run the patch on a given load order
        private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {

            Console.WriteLine("");
            Console.WriteLine("=================================================");
            Console.WriteLine("Starting NPC Patching...");
            Console.WriteLine("=================================================");
            Console.WriteLine("");

            // Loop through all the NPC records in the load order
            foreach (INpcGetter npc in state.LoadOrder.PriorityOrder.Npc().WinningOverrides())
            {
                
                // Skip the player record if the setting is enabled
                if (!settings.PatchPlayerRecord && npc.FormKey.ID == 0x00000007) continue;
                
                // Skip if the replace only default toggle is on
                if (settings.OnlyReplaceDefaulted && npc.Height != 1) continue;

                // Get the race and gender of the NPC
                var race = npc.Race.TryResolve(state.LinkCache);
                var gender = npc.Configuration.Flags.HasFlag(NpcConfiguration.Flag.Female) ? "Female" : "Male";

                // Get the key for the settings dictionary based on the race and gender
                var key = $"{race?.EditorID}";

                if (settings.ScaleEverything) key = "Default";

                // Check if the key exists in the dictionary or is player
                if (settings.RaceGenderSettings.ContainsKey(key))
                {

                    // Create a new NPC record with the modified height and add it to the output mod
                    var modifiedNpc = state.PatchMod.Npcs.GetOrAddAsOverride(npc);

                    // Get the minimum and maximum values from the dictionary
                    var min = settings.RaceGenderSettings[key].MinFemaleHeightScale;
                    var max = settings.RaceGenderSettings[key].MaxFemaleHeightScale;

                    if (gender == "Male") {
                        min = settings.RaceGenderSettings[key].MinMaleHeightScale;
                        max = settings.RaceGenderSettings[key].MaxMaleHeightScale;
                    }

                    // Generate a random height for the NPC within the range using a deterministic seed based on their form ID
                    var seed = npc.FormKey.ID.GetHashCode() + settings.HeightSeed;
                    var random = new Random(seed);
                    var height = Math.Round(min + (max - min) * (float)random.NextDouble(), 3);

                    Console.WriteLine(String.Format("{0} - {1}'s ({2}) height was changed from {3} units to {4} units using seed {5}.",
                            npc.FormKey, modifiedNpc.Name, modifiedNpc.EditorID, modifiedNpc.Height, (float)height, seed));

                    modifiedNpc.Height = (float)height;
                }
                else
                {
                    // Skip the NPC if the key does not exist in the dictionary
                    if (settings.ShowDebugLogs) {
                        Console.WriteLine(String.Format("           {0} - {1} ({2}) skipped due to values for '{3}' not being configured.",
                                npc.FormKey, npc.Name, npc.EditorID, key));
                    }
                    continue;
                }
            }

            Console.WriteLine("");
            Console.WriteLine("=================================================");
            if (settings.PatchFurniture)
            {
                Console.WriteLine("Starting Furniture Patching...");
                Console.WriteLine("=================================================");
                Console.WriteLine("");

                // Loop through all the furniture records in the load order
                foreach (IFurnitureGetter furniture in state.LoadOrder.PriorityOrder.Furniture().WinningOverrides())
                {
                    if (!furniture.HasKeyword(Skyrim.Keyword.RaceToScale)) continue;

                    // Create a new furniture record with the modified height and add it to the output mod
                    var modifiedFurniture = state.PatchMod.Furniture.GetOrAddAsOverride(furniture);
                    modifiedFurniture.Keywords?.Remove(Skyrim.Keyword.RaceToScale);

                    Console.WriteLine(String.Format("{0} - {1}'s ({2}) was patched to disable actor scaling.",
                            furniture.FormKey, modifiedFurniture.Name, modifiedFurniture.EditorID));
                }
            }
            else
            {
                Console.WriteLine("Skipping Furniture Patching...");
                Console.WriteLine("=================================================");
            }
        }
    }
}